export enum NotificationType {
    PLAN_CREATED = 'PLAN_CREATED',
    PLAN_ACTIVATED = 'PLAN_ACTIVATED',
    ROI_PAID = 'ROI_PAID',
    PLAN_MATURED = 'PLAN_MATURED',
    ADMIN_CREATED = 'ADMIN_CREATED',
    USER_CREATED = 'USER_CREATED',
    USER_PASSWORD_RESET = 'USER_PASSWORD_RESET',
    ADMIN_PASSWORD_RESET = 'ADMIN_PASSWORD_RESET',
    USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
    ADMIN_PASSWORD_CHANGED = 'ADMIN_PASSWORD_CHANGED',
}
